ServiceServiceBundle_index:
   path:     /
   defaults: { _controller: "ServiceServiceBundle:Service:index" }
   requirements:
        methods:  GET
ServiceServiceBundle_clear:
   path:     /cache_clear/
   defaults: { _controller: "ServiceServiceBundle:Service:cacheClear" }
   requirements:
        methods:  GET
ServiceServiceBundle_politika:
   path:     /politika/
   defaults: { _controller: "ServiceServiceBundle:Service:politika" }
   requirements:
        methods:  GET
ServiceServiceBundle_support:
   path:     /support/
   defaults: { _controller: "ServiceServiceBundle:Service:support" }
   requirements:
        methods:  GET