<?php

namespace Service\ServiceBundle\Entity\Repository;

/**
 * WorkDay
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkDay extends \Doctrine\ORM\EntityRepository
{
}
